### PR TITLE
Week 2 Tasks

### PR DESCRIPTION
**Pull request by AyserJamshidi**
* Read from configuration file
* Implement detecting a public post
* Implement detecting a private post
* Create UML diagram
* Implement Discord Webhooks
* Implement Discord JDA Bot
* Implement Edge compatibility
* Implement Firefox compatibility
* Pass GeeTest captcha automatically

### CODE REVIEW

**Comment by apsawicki** [comment]
driver automatic downloading works with both windows and mac, discord message sending implementation works as well. Looks good for merge

**Comment by Jsmalriat** [comment]
Implementation for all 3 browsers works, driver auto downloads, output is sent to discord when Token and channel are assigned in config. Good to merge.

**Comment by csaputro** [comment]
Driver auto downloads and was able to run all 3 drivers. Discord bot sends output to intellij and everything runs smoothly. Ok to merge

**Comment by 3cbb** [comment]
Identified distinguishing characteristic between public and private posts, finding a way to implement that distinction using selenium is in progress.

**Review by apsawicki — APPROVED** [review]
driver automatic downloading works with both windows and mac, discord message sending implementation works as well. Looks good for merge

**Pull request merged**
