### PR TITLE
Week 3 Tasks

### PR DESCRIPTION
**Pull request by AyserJamshidi**

### CODE REVIEW

**Review by apsawicki — COMMENTED** [review]
Everything looks good, changes are as implied, ready to ship for release v0.3

**Comment by csaputro** [comment]
Everything looks good, and it runs perfectly

**Comment by AyserJamshidi** [comment]
Maven packaging and standard compilation/running work properly

**Comment by 3cbb** [comment]
Everything looks good and it runs well on my computer

**Review by Jsmalriat — APPROVED** [review]
Everything looks good and works, v0.3 ready to be released.

**Pull request merged**
