### PR TITLE
Week 5 Tasks

### PR DESCRIPTION
**Pull request by AyserJamshidi**

### CODE REVIEW

**Comment by AyserJamshidi** [comment]
Passed all JUnit tests.  All features and functionality work perfectly.

**Comment by apsawicki** [comment]
JUnit tests look good, new JSONHelper file seems to work and post saving seems to work.

**Comment by csaputro** [comment]
README looks clean, test file works well, URLCheck is working, everything looks good

**Review by Jsmalriat — APPROVED** [review]
Testing looks good, Bot and application run smoothly. Ready for public release.

**Pull request merged**
